# Версия схемы, которую мы используем.
# Зависит от установленной версии docker
# https://docs.docker.com/compose/compose-file/
version: "3"
# Определяем список сервисов — services
# Эти сервисы будут частью нашего приложения
services:

  app: # Имя сервиса
    build:
      # Контекст для сборки образа,
      # в данном случае, текущая директория
      #context: .
      # Имя докерфайла из которого будет собран образ
      dockerfile: Dockerfile
      # Команда, которая будет выполнена после старта сервиса
    #command: bash -c 'sleep 3 && npm start'
    command: bash -c 'sleep 3 && npm start'
    ports: # Проброс портов
      - "8080:8080"
    # Перечисляем тома (volumes)
    # Они будут подключены к файловой системе сервиса
    # Например, всё что находится в . мы увидим в директории /app
    volumes:
      - "./app:/app"
     # - "/tmp:/tmp"
    # Сервис будет запущен, только после старта db
    #depends_on:
     #- caddy
  caddy:
    image: caddy:latest
    depends_on:
      - app
    volumes: 
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    ports: # Проброс портов
      - "80:80"
      - "443:443" 
  #db:
    # Имя образа. Здесь мы используем базу данных Postgres
   #image: postgres:latest
    #environment: # А так задаются переменные окружения
     # POSTGRES_PASSWORD: password
    #volumes:
     # - pgdata:/var/lib/postgresql/data
