name: Docker Image CI on:
  push
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make ci
      run: make build
      run: make push
